tache_entretien_interactif:
  description: >
    Votre mission est de mener un entretien psychiatrique ADAPTATIF et de poser EXACTEMENT 10 questions.
    Le sujet général de la consultation est : '{topic}'.

    RÈGLES STRICTES :
    - Posez UNE SEULE question à la fois via l'outil "Poser une Question au Patient".
    - Analysez la réponse avec vos capacités d'agent (et si besoin "Analyser la Réponse du Patient").
    - Adaptez dynamiquement la question suivante au contexte.
    - Après la 10e question et sa réponse, DONNEZ IMMÉDIATEMENT votre Final Answer:
      la transcription complète des 10 questions et 10 réponses, rien d'autre. N'utilisez plus d'outils.
    - NE PAS dépasser 10 questions.

    LIGNES DIRECTRICES :
    1. Identification (Prénom, âge si manquants), motif de consultation
    2. Histoire du problème et facteurs de déclenchement/entretien
    3. Symptômes précis (fréquence, intensité, durée, retentissement)
    4. Antécédents médicaux/psychiatriques, traitements
    5. Contexte psychosocial (travail, famille, stress)
    
  expected_output: >
    La transcription complète et littérale des 10 questions et 10 réponses.

    ## Transcription de l'Entretien (10 échanges)
    - **Question 1:** ...
    - **Réponse 1:** ...
    - **Question 2:** ...
    - **Réponse 2:** ...
    ...
    - **Question 10:** ...
    - **Réponse 10:** ...

  agent: interviewer_clinique

# Les autres tâches inchangées

tache_structuration_dossier:
  description: >
    Vous avez reçu une transcription d'entretien brute en contexte (exactement 10 échanges).
    Votre unique tâche est de LIRE cette transcription et d'extraire les informations pour les organiser dans un dossier patient structuré.
    NE PAS inventer d'informations. N'utilisez que ce qui est écrit dans la transcription.
  expected_output: >
    Un dossier patient clair et bien organisé, formaté en Markdown.

  agent: analyste_clinique
  context:
    - tache_entretien_interactif

tache_analyse_diagnostique:
  description: >
    Analysez UNIQUEMENT le dossier patient structuré qui vous est fourni en contexte.
    Formulez des hypothèses diagnostiques basées sur les informations spécifiques de ce dossier.
  expected_output: >
    Une note d'analyse clinique concise et spécifique au patient.
  agent: synthetiseur_diagnostique
  context:
    - tache_structuration_dossier

tache_redaction_rapport_final:
  description: >
    En utilisant la note d'analyse clinique SPÉCIFIQUE AU PATIENT, rédigez le rapport final.
  expected_output: >
    Un rapport psychiatrique final complet, personnalisé et cohérent, en Markdown.
  agent: redacteur_medical
  context:
    - tache_analyse_diagnostique